kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv01
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/shencheng/workdir/test-k8s/pv_dir/data01"

