apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  containers:
  - name: nginx
    image: nginx
    #    env:
    #    - name: ilike
    #      valueFrom:
    #        configMapKeyRef:
    #          name: colors
    #          key: favorite
    # envFrom:
    # - configMapRef:
    #     name: colors
    volumeMounts:
    - name: car-vo1
      mountPath: /etc/cars
  volumes:
  - name: car-vo1
    configMap:
      name: fast-car
